kubos/kubos-linux-build

- overlay/etc/inittab
- overlay/home/etc/init.d/rcK
- overlay/home/etc/init.d/rcS
User init scripts will be installed into /home/etc/init.d.
Updated inittab to call new rcS script to start them after starting all of the system/Kubos scripts in /etc/init.d. Reverse order for calling rcK to stop everything during shutdown
> [KUBOS-340] Updating overlay to run user init scripts

- circle.yml
- test.sh
This is a super basic integration test that builds the Kubos-Linux image. 
It takes about an hour to run so running it as a nightly build may be a better way to go depending on how it works initially.
> KUBOS-410 Initial integration test circle config

- package/kubos-telemetry/kubos-telemetry.mk
This PR implements the functionality to pull the kubos repo and build the telemetry service module as a buildroot package.
There's a couple of issues with the telemetry module that have surfaced here:
* The build artifact created by the telemetry build configuration is a static library.
* The test directory code contains some compiler errors (with the iOBC tool chain)
> KUBOS-407 Building the telemetry service module from the main kubos repo

- package/kubos-command-and-control/kubos-command-and-control.mk
- package/kubos-telemetry/kubos-telemetry.mk
This should run the kubos `update` command much less frequently. 
This PR also includes  linking the cloned modules rather than kubos-cli modules. This is beneficial as links modules that have already been checked out rather than duplicating a checkout call through the CLI as well.
> KUBOS-439 Lazy loading the kubos version

- board/kubos/at91sam9g20isis/at91sam9g20isis.dts
- board/kubos/at91sam9g20isis/linux/0002-Kubos-spidev.patch
Updating the linux device tree to add the iOBC supervisor as a generic SPI0 device. It can be accessed in userland through the `/dev/spi0.2` device. (The name is /dev/{spiBus}.{chipSelect}).
The tiny patch is because of [this](https://github.com/raspberrypi/linux/issues/1054). By manually defining "spidev" as a valid ID, I'm muting the stack trace that would otherwise get dumped. It doesn't actually change any functionality. Also adding a device name specifically for the supervisor, since it doesn't follow the usual SPI communication protocol (delayed bytes)
This has not been formally tested yet, since there is a fair amount of groundwork in order to send a minimal message to the supervisor. Testing will be done as part of [KUBOS-445](https://kubostech.atlassian.net/browse/KUBOS-445) …
> [KUBOS-423] Adding SPI0 +supervisor support

- board/kubos/at91sam9g20isis/users.txt
- overlay/etc/init.d/rcK
- overlay/etc/init.d/rcS
- overlay/etc/profile
Moving /home/{usr,etc,var} directories to be under /home/system/{usr,etc,var}. This keeps us within the Linux standard where everything under the /home directory belongs to a user.
> [KUBOS-466] Migrating files to /home/system and adding new user

- board/kubos/at91sam9g20isis/users.txt
- overlay/etc/init.d/S99kubos-verify
Tested the default user 'kubos' and found a couple problems:
1. The default user shell is supposed to be /bin/sh, which comes from Busybox.
2. Since the '/home' directory exists outside of the rootfs (because it's actually the user data partition), we can't use the normal rootfs overlay to create the default /home/kubos directory. So instead we'll create it, if necessary, at boot time.
> [KUBOS-526] Fixing default user shell and home directory

- board/kubos/at91sam9g20isis/linux/0001-Kubos-ISIS-Watchdog.patch
Using arch_initcall instead of module_platform_driver in order to initialize the watchdog sooner during kernel boot. This saves us just enough time to stay within the iOBC's one second watchdog starvation timeframe
> [KUBOS-444] Fixing the iOBC watchdog start process

- tools/at91sam9g20isis/kubos-nor-flash.tcl
Created a TCL script to interface with the SAM-BA flashing utility and flash the U-Boot, dtb, and alt OS files (TCL is the only thing they support...)
This script will be passed as an argument when calling the SAM-BA flashing utility:
$ {path to SAM-BA}/sam-ba.exe \jlink\ARM0 at91sam9g20-ISISOBC kubos-nor-flash.tcl {input arguments} [> {logfile}]
Inputs:
* uboot={uboot file} - Path to U-Boot binary
* dtb={dtb file} - Path to Device Tree binary
* altos={alt file} - Path to alternate OS binary
Notes: 
- I put this script in it's own folder because I'm 100% sure it will never be used for another board. The other scripts, I'm less sure.
- This file is not currently intended to run on Linux, which means in order to use it it must be copied onto a Windows machine. But it's going to continue …
> [KUBOS-441] Adding NOR flashing script

- board/kubos/pumpkin-mbm2/pumpkin-mbm2.dts
- Turning on the buses which Pumpkin needs, but aren't enabled with the default BBB device tree
Documentation changes have been made in kubostech/kubos#172
Note: The SPI bus isn't documented. This is because the user's shouldn't be messing with it. The only chip select pin available will be dedicated to the SD over SPI device.
- Integration tests have not yet been added for the MBM2 board
> Turning on desired BBB buses

- board/kubos/at91sam9g20isis/at91sam9g20isis.dts
- Enabling UART0 and UART2
kubostech/kubos#187
> Enabling iOBC UARTs

- tools/format-image.sh
- tools/format-sd.sh
- tools/kubos-kernel.sh
- tools/kubos-nor-package.sh
- tools/kubos-package.sh
Afraid I broke things in #68 
Sorry 🤦‍♂️ 
`:` is a bash no-op, which prevents bash trying to execute the default arg to BASE_DIR (See https://stackoverflow.com/a/4437588 )
The scripts themselves don't actually run until #72 is merged. Let me know if they should be combined.
> Fix tool scripts trying to execute the BASE_DIR default set.

- board/kubos/beaglebone-black/overlay/etc/network/interfaces
- board/kubos/pumpkin-mbm2/overlay/etc/network/interfaces
Docs updated at https://github.com/kubostech/kubos/pull/220
Default IP clashes with public IP ranges.
> Fix default IP Address for BBB / Pumpkin MBM2

- common/overlay/etc/init.d/S99kubos-verify
Because of the spaces at the front of this script, the init script was *NEVER* being run, meaning bootcount was being continually increased, causing every 3rd boot after a flash to attempt recovery.
This took *way* too long to debug.
No documentation changes are needed
Unsure if you have a testing framework for this...?
> Fix more hashbangs.

- board/kubos/at91sam9g20isis/iobc-common.dtsi
- Updating the iOBC's device tree to define the second SPI bus to KubOS Linux (available through the daughterboard). This bus comes with 3 chip select pins, which are defined as generic SPI devices.
kubostech/kubos#221
kubostech/kubos#221
> Enabling iOBC SPI Bus 1 Access

- README.md
- build.sh
- tools/format-image.sh
- tools/format-sd.sh
- tools/kpack-NOR.its
- tools/kubos-kernel.sh
- tools/kubos-nor-package.sh
- tools/kubos-package.sh
Updating all documentation and scripts to refer to the current version of the BuildRoot LTS release
> Upgrading to BuildRoot LTS 2017.02.8

- package/kubos/Config.in
- package/kubos/kubos-mai400/Config.in
- package/kubos/kubos-mai400/kubos-mai400
- package/kubos/kubos-mai400/kubos-mai400.mk
- package/kubos/kubos.mk
A Kubos service for interacting with MAI-400 ADACS has been added with kubos/kubos#61. This PR adds a KLB package to allow automated building and installation of the service.
_Note: This service is not enabled by default, since systems are not guaranteed to have an MAI-400 device present._
Additionally, the main Kubos Makefile has been updated to support a new variable `CARGO_TARGET` for use by pure-Rust Kubos packages.
- Rust docs can be manually generated for the service, but have not been included in the main Kubos docs page. [The work to enable such inclusion is still in To-Do](https://trello.com/c/EhSNE9dZ/243-integrate-rust-docs-into-main-docs)
- The change log hasn't been updated yet and will need to be changed before the next release. …
> Adding KLB package for MAI-400 Kubos service

- dist/Dockerfile
When I updated the kubos-linux-dev Docker image to include Rust, I then ran into a missing-dependency problem when building. This PR adds the dependency (cpio)
> Adding cpio dependency to Dockerfile

- common/overlay/home/system/etc/config.toml
From the Trello card:
```
Right now each KubOS Service (hardware or not) reads it's own address and port number from a section in `/home/system/etc/config.toml`. Some services (like telemetry) will actually fail to start if the config section is missing, others will fall back to `127.0.0.1:8080`. 
Long term, we need to explicitly state which service lives on what port so that there are no conflicts or user configuration required out of the box.
```
So I copied the current version of our config.toml into the `common/overlay/home/system/etc` folder with the expectation that any time a new service is made and the KLB package for it is created, this file should be updated to add the new default configuration options.
Users can then modify this file to remove or change any options they like …
> Adding default config.toml file for Kubos services

- package/kubos/kubos-core/Config.in
- package/kubos/kubos-core/kubos-core-lua/Config.in
The lua package is a place holder until it is broken out and converted to Rust packages. Turns out it does still need a Config.in file in order to be automatically built in >.>
> Adding hidden Kubos core lua package option

- common/overlay/home/system/etc/config.toml
- package/kubos/Config.in
- package/kubos/kubos-isis-ants/Config.in
- package/kubos/kubos-isis-ants/kubos-isis-ants
- package/kubos/kubos-isis-ants/kubos-isis-ants.mk
The Kubos service for ISIS antenna systems is finally landing (kubos/kubos#53)
This PR adds the corresponding KLB package and updates the default `config.toml` file with the relevant configuration options.
> Adding package for AntS service

- tools/kpack.its
- tools/kubos-package.sh
CircleCI refuses to allow loopback devices to be used. There was still one in the `kubos-package.sh` script, preventing the kpack-base.itb file from being created.
> Removing need for loopback device in aux SD generation

- package/kubos/kubos-core/kubos-core-app-service/kubos-core-app-service
Adding `-b` flag to app service initialization call to trigger the `OnBoot` logic for all registered apps
> Adding -b flag to app service init

- package/kubos/kubos-pumpkin-mcu/kubos-pumpkin-mcu
The underlying kubos-service python package was updated to take the configuration file as a command line option rather than a positional argument. Updating the init script to reflect that.
> Fixing Pumpkin MCU service init script

- package/kubos/kubos-clyde-3g-eps/kubos-clyde-3g-eps.mk
- package/kubos/kubos-core/kubos-core-app-service/kubos-core-app-service.mk
- package/kubos/kubos-core/kubos-core-telemetry-db/kubos-core-telemetry-db.mk
- package/kubos/kubos-isis-ants/kubos-isis-ants.mk
- package/kubos/kubos-mai400/kubos-mai400.mk
- package/kubos/kubos-novatel-oem6/kubos-novatel-oem6.mk
We have updated our Rust crates to use Failure v0.1.2. This version of `failure` uses `backtrace`, which uses `backtrace-sys`, which uses `cc`.
The `cc` crate doesn't properly fetch the cross-compiling toolchain. This causes builds to fail for the iOBC target (and magically works for the BBB, but I don't trust it). The solution is to manually specify the location of the gcc. 
This PR adds a CC envar to all of our packages which build Rust crates
> Manually specifying CC for Rust crates

- common/overlay/home/system/etc/config.toml
- package/kubos/Config.in
- package/kubos/kubos-app-api/Config.in
- package/kubos/kubos-app-api/kubos-app-api.mk
- package/kubos/kubos-hal-i2c/Config.in
- package/kubos/kubos-hal-i2c/kubos-hal-i2c.mk
- package/kubos/kubos-monitor/Config.in
- package/kubos/kubos-monitor/kubos-monitor
- package/kubos/kubos-monitor/kubos-monitor.mk
- package/kubos/kubos-pumpkin-mcu/Config.in
- package/kubos/kubos-service-lib/Config.in
- package/kubos/kubos-service-lib/kubos-service-lib.mk
This PR adds packages for the following items from the kubos repo:
- apis/app-api/python
- hal/python-hal/i2c
- libs/kubos-service
- services/monitor-service
All of the new packages are included by default except for `kubos-service`. That's because there are a couple incompatibilities between its dependencies, buildroot, and CircleCI. These issues may be fixed in the future with [the upgrade to the newer buildroot LTS](https://trello.com/c/Edbd9Rup/29-migrate-to-new-buildroot-lts-version)
> Adding packages for custom Python modules and monitor service

- package/kubos/Config.in
- package/kubos/kubos-pumpkin-mcu-api/Config.in
- package/kubos/kubos-pumpkin-mcu-api/kubos-pumpkin-mcu-api.mk
- package/kubos/kubos-pumpkin-mcu/Config.in
The Pumpkin MCU service depends on the corresponding MCU API. Adding a new package to get it built into Kubos Linux.
Also fixing a typo...
> Adding package for Pumpkin MCU API

- common/overlay/etc/rsyslog.conf
- common/overlay/etc/rsyslog.d/kubos-apps.conf
- common/overlay/etc/rsyslog.d/kubos-services.conf
- common/overlay/home/system/kubos/apps-rotate.sh
- common/overlay/home/system/kubos/kubos-rotate.sh
- common/overlay/home/system/kubos/system-rotate.sh
- common/user-overlay/system/kubos/apps-rotate.sh
- common/user-overlay/system/kubos/kubos-rotate.sh
Updating all logging policies to add a max size (1MB). When the max size is hit, the appropriate rotation script will be called to archive the current file. If there are already 5 archive files for that particular log, the oldest is deleted.
Note: The `rsyslog.conf` file here was just copied from the default file and then updated to use the rotation logic. The default policies and log files have remained the same.
TODO (in a different PR)
None
> Adding default logging rotation policies and scripts

- tools/release-test/run_test.sh
The file client tweaked the way it checks its arguments. This PR updates the release test to comply with this new ordering
> Updating release test to comply with new file client format

- board/kubos/beaglebone-black/genimage.cfg
- board/kubos/beaglebone-black/overlay/etc/fstab
- board/kubos/beaglebone-black/overlay/etc/fw_env.config
- board/kubos/beaglebone-black/overlay/etc/inittab
- board/kubos/pumpkin-mbm2/genimage.cfg
- board/kubos/pumpkin-mbm2/overlay/etc/fstab
- board/kubos/pumpkin-mbm2/overlay/etc/fw_env.config
- board/kubos/pumpkin-mbm2/overlay/etc/inittab
Updates the BBB and MBM2 configs to move the U-Boot envars into a new partition in the main Kubos Linux SD image.
The two boards are grouped together in this single PR because the changes are identical.
The `genimage.cfg` changes are what actually creates the new partition.
All other changes are used to mount the new partition for use by the `fw_printenv` and `fw_setenv` commands from the Linux command line
**kubos-linux.img:**
| Partition | Old Contents        | New Contents        |
|-----------|---------------------|---------------------|
| 1         | U-Boot, kernel, DTB | U-Boot, kernel, DTB |
| 2         | RootFS              | RootFS              |
| 3         | User Partition      | U-Boot Envars       |
| 4         | -- Doesn't Exist -- | User Partition      | …
> Moving BBB/MBM2 U-Boot envars to own partition

- board/kubos/at91sam9g20isis/overlay/etc/monitrc
- board/kubos/beaglebone-black/overlay/etc/monitrc
- board/kubos/pumpkin-mbm2/overlay/etc/monitrc
For some reason, when the `kubos` user runs `monit status` it is unable to correctly guess the location of the PID file of the monit daemon to then query the process for its current status information.
This PR manually sets the PID file location (which is just the default location) so that `monit status` can be run from the command line by any user.
> Explicitly declaring Monit's PID file

- board/kubos/at91sam9g20isis/overlay/etc/inittab
- board/kubos/beaglebone-black/overlay/etc/inittab
- board/kubos/pumpkin-mbm2/overlay/etc/inittab
- common/overlay/etc/init.d/S99kubos-verify
- Add `sync` after changing boot count
-  Run `fsck` against writeable partitions during boot
1. No documentation changes are needed
> Check boot corruption

- tools/release-test/run_test.sh
- tools/release-test/src/app_service.rs
UUIDs were removed from the app service with kubos/kubos#305
Updating the release test to be compatible with the new format
> Removing app UUID from release test

- tools/kubos-package.sh
- Manually adding the BBB toolchain to PATH so that the `dtc` executable can be found when this script is run outside of the full build process
- Bumping the default U-Boot version to our latest version number
- Removing the `-k` option because it isn't used by anything
Relevant doc changes have been made in kubos/kubos#398
> Updating upgrade package creation script

- README.md
The Great Docs Re-Org of 2019 (kubos/kubos#354) is moving docs around.
This PR updates the readme to use the new locations.
Also updating the listed version of buildroot that we're using
> Updating the readme with the new doc links

- package/kubos/kubos-clyde-3g-eps/kubos-clyde-3g-eps.mk
- package/kubos/kubos-core/kubos-core-app-service/kubos-core-app-service.mk
- package/kubos/kubos-core/kubos-core-file-transfer/kubos-core-file-transfer.mk
- package/kubos/kubos-core/kubos-core-shell/kubos-core-shell.mk
- package/kubos/kubos-core/kubos-core-telemetry-db/kubos-core-telemetry-db.mk
- package/kubos/kubos-isis-ants/kubos-isis-ants.mk
- package/kubos/kubos-mai400/kubos-mai400.mk
- package/kubos/kubos-monitor/kubos-monitor.mk
- package/kubos/kubos-novatel-oem6/kubos-novatel-oem6.mk
- package/kubos/kubos-nsl-duplex/kubos-nsl-duplex.mk
Adding `--package {crate name}` to each Rust package to ensure no extraneous code gets built
> Ensuring only the current package is built with 'cargo build'

- tools/release-test/README.rst
- tools/release-test/run_test.sh
- tools/release-test/src/app_service.rs
- tools/release-test/src/monitor_service.rs
- tools/release-test/src/telem_service.rs
This PR updates the release test in response to two changes we have made:
- kubos/kubos#372 - The file transfer service now requires that the downlink IP and port be defined
- kubos/kubos#431 - Service config initialization now returns a `Result`, failing when errors are encountered instead of taking default values
> Updating release test for file transfer downlink & gen service config

- common/linux-kubos.config
For *some* reason, when Buildroot goes to create the Linux configuration file for the MBM2 by combing the common linux config and the mbm2-specific config, the `CONFIG_LOCALVERSION` value gets set to `""` instead of `"-KubOS-0.0.0"`. I was unable to figure out how long this has been an issue for, but it goes back to atleast v1.10.
This problem *does not* occur for the BBB, which has an almost identical configuration :/
I fixed the issue by adding a comment line to the top of the common config file. It does not functionally change anything. But is completely necessary, apparently.
> Fixing CONFIG_LOCALVERSION for MBM2

- tools/release-test/src/app_service.rs
The app service schema changed with kubos/kubos#445
Updating the release test to use the new query name and add an app monitoring query
> Updating app service query

- package/kubos/kubos-core/Config.in
- package/kubos/kubos-core/kubos-core-scheduler/Config.in
- package/kubos/kubos-core/kubos-core-scheduler/kubos-core-scheduler
- package/kubos/kubos-core/kubos-core-scheduler/kubos-core-scheduler.mk
CI will fail until kubos/kubos#443 has been merged.
If CI continues to fail afterwards, check out the `BR_COMPILER_PARANOID_UNSAFE_PATH` option. (It somehow got turned on in my test build. It's possible I did that on purpose when poking around at some point, but I don't remember)
**NOTE**: The default ``schedules_dir`` value is currently different than what is documented. I set it this way to better match the app and telemetry services. Maybe change this value before finally merging
> Adding scheduler package

- README.md
- Description of what this PR is for and high-level overview of what was changed
The link to the Kubos Linux documentation in the README file is broken for versions >1.15.
This commit changes the target url to the new location inside the web documentation.
Only documentation changes
> Fix link to Kubos Linux documentation in README

- package/kubos/kubos-clyde-3g-eps/kubos-clyde-3g-eps.mk
- package/kubos/kubos-core/kubos-core-app-service/kubos-core-app-service.mk
- package/kubos/kubos-core/kubos-core-file-transfer/kubos-core-file-transfer.mk
- package/kubos/kubos-core/kubos-core-scheduler/kubos-core-scheduler.mk
- package/kubos/kubos-core/kubos-core-shell/kubos-core-shell.mk
- package/kubos/kubos-core/kubos-core-telemetry-db/kubos-core-telemetry-db.mk
- package/kubos/kubos-isis-ants/kubos-isis-ants.mk
- package/kubos/kubos-mai400/kubos-mai400.mk
- package/kubos/kubos-monitor/kubos-monitor.mk
- package/kubos/kubos-novatel-oem6/kubos-novatel-oem6.mk
- package/kubos/kubos-nsl-duplex/kubos-nsl-duplex.mk
On my machine, setting `CC=$(TARGET_CC)` was insufficient for rust to find the correct linker and compile packages. Setting `-Clinker=$(TARGET_CC)` is a more robust way to provide the correct linker to `rustc`.
> Allow rust packages to find the linker correctly

- package/kubos/kubos-core/kubos-core-app-service/kubos-core-app-service
Run levels and the `-b` "OnBoot" flag for the app service were removed in kubos/kubos#457. This PR updates the app service init script to remove that flag.
> Removing '-b' flag from app service init script
